# Generated by Django 5.2 on 2025-08-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_uwagi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uwagi',
            new_name='Uwaga',
        ),
    ]
