# Generated by Django 5.2 on 2025-08-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_uwagi_uwaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='uwaga',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
