# Generated by Django 5.2 on 2025-08-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_uwaga_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='uwaga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
